using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;

namespace SurfOS2
{
    internal class Core_Engine
    {
        // =========================================================================
        // DEEP WINDOWS API HOOKS FOR WINDOW MANAGEMENT (user32.dll)
        // =========================================================================

        [DllImport("kernel32.dll", ExactSpelling = true)]
        private static extern IntPtr GetConsoleWindow();

        [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

        private const int SW_MAXIMIZE = 3;
        private const short HugeConsoleFontSize = 36;

        /// <summary>
        /// Forces the console window to maximize to full screen.
        /// </summary>
        public static void MaximizeWindow()
        {
            if (!OperatingSystem.IsWindows()) return;

            try
            {
                IntPtr consoleWindowHandle = GetConsoleWindow();
                if (consoleWindowHandle != IntPtr.Zero)
                {
                    ShowWindow(consoleWindowHandle, SW_MAXIMIZE);
                }
            }
            catch
            {
                // Failsafe in case the OS blocks the window resize
            }
        }


        // 🛑 YOUR MASTER SECRET: Keep this identical to the one on your website!
        private const string OS_SECRET_KEY = "73 75 72 66 6F 73 5F 74 68 65 6D 65 3D 37 39 32 30 33 34 35 37 34 33 35 38 37 35 34 34 35 36 34 39 35 31 34 35 30 39 32 37 33 36 31 30 33 38 31 35 34 38 36 37 32 35";

        /// <summary>
        /// Mathematically proves if the theme file was generated by your official website.
        /// </summary>
        public static bool IsThemeLegit(Import.SurfTheme theme)
        {
            if (string.IsNullOrEmpty(theme.AuthorSignature)) return false;

            // 🌟 NEW: Added WelcomeMessage and PromptStyle to the hash!
            string rawData = $"{theme.ThemeName}{theme.TargetColor}{theme.FontName}{theme.WelcomeMessage}{theme.PromptStyle}{OS_SECRET_KEY}";

            byte[] hash = SHA256.HashData(Encoding.UTF8.GetBytes(rawData));
            string expectedHash = Convert.ToHexStringLower(hash);
            return string.Equals(
                expectedHash,
                theme.AuthorSignature,
                StringComparison.OrdinalIgnoreCase);
        }

        // =========================================================================
        // DEEP WINDOWS API HOOKS FOR FONT CHANGING (kernel32.dll)
        // =========================================================================
        [DllImport("kernel32.dll", SetLastError = true)]
        static extern IntPtr GetStdHandle(int nStdHandle);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        static extern bool GetCurrentConsoleFontEx(IntPtr hConsoleOutput, bool bMaximumWindow, ref CONSOLE_FONT_INFO_EX lpConsoleCurrentFontEx);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        static extern bool SetCurrentConsoleFontEx(IntPtr consoleOutput, bool maximumWindow, ref CONSOLE_FONT_INFO_EX consoleCurrentFontEx);

        private const int STD_OUTPUT_HANDLE = -11;

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        public struct CONSOLE_FONT_INFO_EX
        {
            public uint cbSize;
            public uint nFont;
            public short dwFontSizeX;
            public short dwFontSizeY;
            public int FontFamily;
            public int FontWeight;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
            public string FaceName;
        }

        /// <summary>
        /// Forces the Windows Console to change its font face and ensures a readable size.
        /// </summary>
        public static void SetConsoleFont(string fontName)
        {
            if (!OperatingSystem.IsWindows()) return;

            try
            {
                IntPtr hnd = GetStdHandle(STD_OUTPUT_HANDLE);
                CONSOLE_FONT_INFO_EX fontInfo = new CONSOLE_FONT_INFO_EX();
                fontInfo.cbSize = (uint)Marshal.SizeOf(fontInfo);

                GetCurrentConsoleFontEx(hnd, false, ref fontInfo);

                fontInfo.FaceName = GetPathSafeFontName(fontName);

                // 🌟 FIX: Force a larger default size! (24 is usually a great sweet spot)
                fontInfo.dwFontSizeY = 24;
                fontInfo.dwFontSizeX = 0; // Auto-scales the width

                SetCurrentConsoleFontEx(hnd, false, ref fontInfo);
            }
            catch { }
        }

        private static string GetPathSafeFontName(string fontName)
        {
            if (fontName.Equals("MS Gothic", StringComparison.OrdinalIgnoreCase) ||
                fontName.Equals("MS PGothic", StringComparison.OrdinalIgnoreCase) ||
                fontName.Equals("MS UI Gothic", StringComparison.OrdinalIgnoreCase))
            {
                return "Consolas";
            }

            return string.IsNullOrWhiteSpace(fontName) ? "Consolas" : fontName;
        }

        /// <summary>
        /// Allows the user to dynamically scale the UI text size up or down.
        /// </summary>
        public static void ChangeFontSize(short newSize)
        {
            if (!OperatingSystem.IsWindows()) return;

            try
            {
                IntPtr hnd = GetStdHandle(STD_OUTPUT_HANDLE);
                CONSOLE_FONT_INFO_EX fontInfo = new CONSOLE_FONT_INFO_EX();
                fontInfo.cbSize = (uint)Marshal.SizeOf(fontInfo);

                GetCurrentConsoleFontEx(hnd, false, ref fontInfo);

                fontInfo.dwFontSizeY = newSize;
                fontInfo.dwFontSizeX = 0;

                SetCurrentConsoleFontEx(hnd, false, ref fontInfo);
            }
            catch { }
        }

        /// <summary>
        /// Uses the prominent text size reserved for the boot and login screens.
        /// </summary>
        public static void UseHugeConsoleText() => ChangeFontSize(HugeConsoleFontSize);

    }
}
